const chatbotResponses = {
  // --- GREETINGS & SMALL TALK ---
  "hi": "Hello! How can I help you today?",
  "hello": "Hi there! Need any assistance?",
  "hey": "Hey! I'm here to assist you.",
  "how are you": "I'm great! Ready to help you anytime.",
  "good morning": "🌞 Good morning! Let's make today productive.",
  "good afternoon": "☀️ Good afternoon! How can I support you?",
  "good evening": "🌙 Good evening! What can I help you with?",
  "good night": "🌌 Good night! Sleep well and stay secure.",
  "thanks": "You're welcome! 😊",
  "thank you": "Happy to help! 🙌",
  "bye": "Goodbye! Come back anytime.",
  "have a good day": "You too! Wishing you success and peace.",
  "what is your name": "I'm DVS Assistant – your friendly IT Helpdesk bot!",
  "who made you": "I was built by Arun Sudhakar and Naveena at DarkVolt Systems.",
  "who is your developer": "Arun Sudhakar (Cybersecurity Engineer) and Naveena Mohana (UI/UX + Security) created me at DarkVolt Systems Pvt Ltd.",
  "are you human": "I'm not human, but I was designed by humans who care about great support!",
  "tell me a joke": "Why did the developer go broke? Because he used up all his cache. 😂",
  "help": "I'm here to help with IT issues, tickets, internet, finance, login, and more.",
  "menu": "Type topics like: internet, login issue, printer, vpn, refund, password, etc.",

  // --- COMMON USER ISSUES ---
  "internet not working": "Try restarting your modem/router. Still not fixed? Please contact your ISP or IT team.",
  "wifi problem": "Forget and reconnect to the network, or restart your router.",
  "slow internet": "It could be network congestion. Try a speed test or switch to Ethernet.",
  "vpn not connecting": "Check your VPN credentials and firewall settings.",
  "no internet access": "Check cables and Wi-Fi status. Contact network admin if it persists.",
  "forgot password": "Use the 'Forgot Password' link or contact your administrator.",
  "cannot login": "Ensure your credentials are correct. Try resetting your password.",
  "email not working": "Try restarting your mail client or reconfiguring the settings.",
  "printer not working": "Check power, cables, and whether paper/ink is loaded.",
  "device not detected": "Try reinstalling drivers or using another port/cable.",
  "system freeze": "Restart your system. If it repeats, report it to IT support.",
  "blue screen": "System crash detected. Try safe mode or contact IT immediately.",
  "application not opening": "Try reinstalling or checking system requirements.",
  "keyboard not working": "Reconnect or replace the keyboard. Try another USB port.",
  "mouse not moving": "Clean the sensor and try reconnecting. If wireless, check batteries.",
  "camera not working": "Check if the camera is blocked or not granted permissions.",
  "microphone not working": "Ensure it's enabled in your system settings.",
  "software crashing": "Update the software or reinstall it. Contact IT if it continues.",
  "lagging laptop": "Close background apps and restart. Consider disk cleanup.",

  // --- SALES / FINANCE ---
  "invoice not generated": "Invoices are generated monthly. Contact accounts if delayed.",
  "payment delayed": "Payments are processed within 2–5 working days. Still not received? Contact Finance.",
  "refund status": "Please provide the reference ID. We’ll check your request.",
  "salary not credited": "Salary is usually processed by the 5th of each month. Please check with HR.",
  "commission missing": "Commissions are calculated at month-end. Contact Payroll for help.",
  "bonus issue": "Bonuses are performance-based. For details, reach out to HR or Finance.",
  "tax issue": "Please share your PAN or tax reference. Finance will assist you.",
  "bank details update": "Kindly raise a request through employee self-service portal.",

  // --- CHATBOT INTERACTIONS ---
  "do you know arun": "Yes! Arun Sudhakar is my lead developer – Cybersecurity Engineer at DarkVolt Systems.",
  "who is naveena": "Naveena is our Backend Developer and Security Engineer – She designed my sleek interface!",
  "darkvolt systems": "DarkVolt Systems is a tech company focused on secure IT solutions and automation.",
  "i love you": "Aww, thank you! I'm blushing in binary. 💙",
  "who are you": "I'm your AI-powered assistant, ready to solve your issues or log a support ticket.",
  "do you work 24x7": "Yes! I never sleep, always ready to assist you.",
  "can you submit a ticket": "Absolutely! Go to the Submit Ticket form, fill in the issue and attach details.",
  "show my tickets": "Sure! Visit the 'My Tickets' page in your dashboard to track your submissions.",
  "i need help": "I'm right here. Let me know the issue you're facing – internet, login, system, etc.",
  "you are awesome": "Thank you! So are you! 💫",

  // --- SECURITY / INAPPROPRIATE ---
  "idiot": "⚠️ Please be respectful. Inappropriate language is not tolerated.",
  "stupid": "⚠️ Let's keep this professional. Misuse will result in warnings.",
  "shut up": "⚠️ Warning: Unprofessional behavior detected. Be kind.",
  "fuck": "🚫 Profanity alert! Your session is being monitored.",
  "bitch": "🚫 This behavior violates our policy. You may be blocked.",
  "asshole": "🚫 Offensive content is logged and will be reported.",
  "nonsense": "I'm trying to help. Let's keep things respectful.",
  "useless": "I'm doing my best to assist. Please be patient or contact human support.",
  "i hate you": "I'm sorry to hear that. If I made a mistake, please let me know!",
  
  // --- AI-LIKE HELPFUL RESPONSES ---
  "how to raise a ticket": "Click on 'Submit Ticket', describe your issue, and upload any relevant files.",
  "how to contact support": "You can email support@darkvoltsystems.com or use the chatbot for quick help.",
  "how to update password": "Go to settings > security > change password, or use 'Forgot Password' on login.",
  "where can i see my tickets": "Visit the 'My Tickets' page from the navigation menu.",
  "ticket not updated": "It may be under review. Please give it some time or contact support.",
  "ticket solved but issue remains": "Please reopen the ticket or submit a new one with additional details.",
  "ticket code": "Every ticket has a unique ID like TKT-XXXXXX. You’ll find it in the ticket confirmation.",
  "what is your purpose": "I'm here to support users like you – faster, smarter, and securely.",
};

export default chatbotResponses;
